services:
  urban_style_db:
    image: mongo:8.0.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    command: ['--replSet', "rs0", '--bind_ip_all', '--port', '27017']
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - urban_style_network

  shopping_cart_db:
    image: redis:8.0-alpine
    container_name: redis_db
    ports:
      - "6379:6379"
    command: ["redis-server", "redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis.conf:/data/redis.conf:Z
    networks:
      - urban_style_network

  urban_style_api:
    image: docker.io/library/urban-style:${VERSION}
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - urban_style_db
      - shopping_cart_db
    env_file:
      - .env.development
    networks:
      - urban_style_network


networks:
  urban_style_network:
    name: urban_style_network
    driver: "bridge"
    ipam:
      config:
        - subnet: 192.168.101.0/24

volumes:
  mongo_data:
  mongo_config:
  redis_data:
